### ISSUE TITLE
POST to /api/v1/contacts does not trigger Double-Opt-In

### ISSUE THREAD

**Issue by verymilan** [pentacent/keila#281] opened 2024-04-04 11:19 UTC
Hi there I've just created a custom form for Keila, but it looks like DOI is not triggered when using the API. This would be a nice addition (unless I use the wrong API call?) – because otherwise my form can't be used unless I somehow figure out how to implement DOI for that form... .

**Comment by verymilan** [comment] 2024-04-04 12:47
I read that for Mailchimp there is a contact status "pending", that can be used with their API. Keila also sets a status, maybe this could be extended to also support "pending" for when this lands on the roadmap? An endpoint for forms sounds nice as well.

**Comment by wmnnd** [comment] 2024-04-04 12:54
That’s not possible because Keila doesn’t actually create contacts for people who sign in via a DOI form. Instead, a "FormParams" entity is created that is once again submitted when a user confirms their email.

**Comment by verymilan** [comment] 2024-04-09 15:02
I apologize for using this issue for the following question, but I don't know where else to go... I have analyzed the POST request from /forms/ and created my own. This ... appears ... to work in the sense that Keila responds with a `200`, but neither is DOI triggered, nor does Keila seem to include the user in the list. 
Is there something special I might need to try?

**Comment by wmnnd** [comment] 2024-04-09 15:20
Are you sure the sender is set up correctly? You can check if your request was registered with `Keila.Repo.all(Keila.Contacts.FormParams)` from IEx.

**Comment by verymilan** [comment] 2024-04-09 15:38
Whoops deleted my comment and right after, Firefox decided to show me that there was a reply. I have updated my request and it now works ... for some reason.

Originally it looked like this: 
`"contact%5Bemail%5D=" + urllib.parse.quote_plus(session['sender']) + "contact%5Bfirst_name%5D=" + session['firstname'] + "&contact%5Blast_name%5D=" + session['lastname']`
Here Keila responded with 200 but nothing happened.

Now it looks like this, I tried to encode this as well (as a whole) but couldn't preserve the `=`, landing me in a `400` (I think thats the reason).:
`"contact[email]=" + session['sender'] + "&" + "contact[first_name]=" + session['firstname'] + "&" + "contact[last_name]=" + session['lastname']`

As long as the `'Content-Type': 'application/x-www-form-urlencoded'` header is present, it now works. Maybe the Python requests library already does some encoding by itself due to me using `requests.post(uri, data ...`? I have not yet tried this in a Keila setup with more logoutput yet. 

But hey it works 😅

**Comment by wmnnd** [comment] 2024-04-09 15:39
How are you making the request? Most languages probably have a library available that helps with the form encoding :wink:

**Comment by wmnnd** [comment] 2024-05-20 09:13
I’ll close this for now because the API is working as intended. We should consider a separate endpoint for creating FormParams/DOI signups in the future.

**Closed by wmnnd** 2024-05-20 09:13 UTC
