### ISSUE TITLE
Bright flash during page transitions

### ISSUE THREAD

**Issue by pascalwengerter** [pentacent/keila#26] opened 2021-02-23 01:11 UTC
Noticed this when navigating around the application locally: Everytime a link is clicked and the browser performs a (full) page transition, there's a tiny white flash screen for half a second - at least for me (Firefox, macOS, Darkmode).

I tried setting `html, body, main {background-color: black}` but that didn' work (since it's arguably a full page reload).

Perhaps Phoenix Liveview isn't fully configured yet to only replace the page content within the `main` tag or something? Guess that one is a quick win!

**Comment by wmnnd** [comment] 2021-02-23 15:57
Where exactly are you getting these flashes? I’m not getting any, neither in dev nor in production. I tried it with Firefox and Chromium on Ubuntu, also with dark mode enabled.

**Comment by pascalwengerter** [comment] 2021-02-24 11:50
Okay that's weird. I get them everytime I navigate around the application (e.g. clicking items in the navbar), let me record it later and see if I can capture it on camera!

**Comment by pascalwengerter** [comment] 2021-02-25 12:22
@wmnnd [here](https://drive.google.com/file/d/1I5-yQ6_jK9TxSL-WTzxN2OP8qM8jbfHA/view?usp=sharing) we are! It doesn't seem to follow a clear rule though...

**Comment by wmnnd** [comment] 2021-02-25 12:49
Do you also get that in production, i.e. after compiling and digesting the assets?
It’s certainly not a LiveView problem because the pages in your clip aren’t live views, so you’re probably right to assume the issue is somewhere to be found within the Webpack config …

**Comment by wmnnd** [comment] 2021-02-25 12:52
There’s actually a topic from today on the Elixir Forum about a similar issue. They seem to be connecting it to LV so far but maybe a solution might come out of there: https://elixirforum.com/t/phoenix-liveview-raw-vs-css-styled-display/37783

**Comment by pascalwengerter** [comment] 2021-02-25 13:22
> There’s actually a topic from today on the Elixir Forum about a similar issue. They seem to be connecting it to LV so far but maybe a solution might come out of there: https://elixirforum.com/t/phoenix-liveview-raw-vs-css-styled-display/37783

Let's call it a bleeding edge issue, then? 😜

Haven't logged into my production instance yet due to lack of seeds, let me know once you've published a new Docker image and I'm happy to check it out there!

**Comment by wmnnd** [comment] 2021-02-25 13:25
The `0.2.0` docker image is already out. Maybe I should have sent a newsletter about that 😅

With your database already initialized, the seeds will also not run. So either you start with an empty database there or manually replicate the steps from `priv/repo/seeds.exs` after getting on IEx with the `remote` command.

**Comment by wmnnd** [comment] 2021-03-29 10:13
I haven’t been able to reproduce it locally and it doesn’t happen in the production deployment on app.keila.io, so I’m closing it for now. Should the issue manifest again, please feel free to reopen.

**Closed by wmnnd** 2021-03-29 10:13 UTC
Labels: needs investigation

**Comment by pascalwengerter** [comment] 2021-03-29 10:14
Sounds reasonable to me! ;)
